name = "epcis"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Resource limits
[limits]
cpu_ms = 50
uploader_size_mb = 100

# Rate limiting configuration
[[rate_limits]]
namespace_id = "epcis_api"
period = 60
limit = 1000

[[kv_namespaces]]
binding = "EPCIS_KV"
id = "example-id"
preview_id = "example-preview-id"

[[analytics_engine_datasets]]
binding = "EPCIS_ANALYTICS"
dataset = "epcis_events"
