name = "epcis"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "EPCIS_KV"
id = "example-id"
preview_id = "example-preview-id"

[[analytics_engine_datasets]]
binding = "EPCIS_ANALYTICS"
dataset = "epcis_events"
